
; general
SendMode, Input

; suspend AHK
LWin & a::Suspend


#Include AnyKey.ahk


; Escape -> Tab -> Ctrl -> CapsLock -> Escape
$Escape::Capslock
$Tab::AnyKey("{Escape}", "CL")
$Capslock::Ctrl
$Ctrl::AnyKey("{Tab}", "`t")

; make \ (left of Enter and closer to right pinky) an additional Enter
$*SC02B::AnyKey("{Enter}", "`n")


; main keys
$*a::AnyKey("a", "a")
$*b::AnyKey("b", "b")
$*c::AnyKey("c", "c")
$*d::AnyKey("s", "s")
$*e::AnyKey("f", "f")
$*f::AnyKey("t", "t")
$*g::AnyKey("d", "d")
$*h::AnyKey("h", "h")
$*i::AnyKey("u", "u")
$*j::AnyKey("n", "n")
$*k::AnyKey("e", "e")
$*l::AnyKey("i", "i")
$*m::AnyKey("m", "m")
$*n::AnyKey("k", "k")
$*o::AnyKey("y", "y")
$*p::AnyKey(";", ";")
$*q::AnyKey("q", "q")
$*r::AnyKey("p", "p")
$*s::AnyKey("r", "r")
$*t::AnyKey("g", "g")
$*u::AnyKey("l", "l")
$*v::AnyKey("v", "v")
$*w::AnyKey("w", "w")
$*x::AnyKey("x", "x")
$*y::AnyKey("z", "z")
$*z::AnyKey("j", "j")
$+a::AnyKey("A", "A")
$+b::AnyKey("B", "B")
$+c::AnyKey("C", "C")
$+d::AnyKey("S", "S")
$+e::AnyKey("F", "F")
$+f::AnyKey("T", "T")
$+g::AnyKey("D", "D")
$+h::AnyKey("H", "H")
$+i::AnyKey("U", "U")
$+j::AnyKey("N", "N")
$+k::AnyKey("E", "E")
$+l::AnyKey("I", "I")
$+m::AnyKey("M", "M")
$+n::AnyKey("K", "K")
$+o::AnyKey("Y", "Y")
$+p::AnyKey(":", ":")
$+q::AnyKey("Q", "Q")
$+r::AnyKey("P", "P")
$+s::AnyKey("R", "R")
$+t::AnyKey("G", "G")
$+u::AnyKey("L", "L")
$+v::AnyKey("V", "V")
$+w::AnyKey("W", "W")
$+x::AnyKey("X", "X")
$+y::AnyKey("Z", "Z")
$+z::AnyKey("J", "J")
; QWERTZ has a lot of characters that collide with ahk and can't be sent directly
; hence the scan codes and key strings
$*SC027::AnyKey("o", "o")
$+SC027::AnyKey("+o", "O")
$*SC029::AnyKey("``{Space}", "`")
$*SC002::AnyKey("1", "1")
$*SC003::AnyKey("2", "2")
$*SC004::AnyKey("3", "3")
$*SC005::AnyKey("4", "4")
$*SC006::AnyKey("5", "5")
$*SC007::AnyKey("6", "6")
$*SC008::AnyKey("7", "7")
$*SC009::AnyKey("8", "8")
$*SC00A::AnyKey("9", "9")
$*SC00B::AnyKey("0", "0")
$*SC00C::AnyKey("-", "-")
$*SC00D::AnyKey("=", "=")
$*SC01A::AnyKey("[", "[")
$*SC01B::AnyKey("]", "]")
$*SC028::AnyKey("'", "'")
$*SC056::AnyKey("\", "\")
$*SC033::AnyKey(",", ",")
$*SC034::AnyKey(".", ".")
$*SC035::AnyKey("/", "/")
$+SC029::AnyKey("{ASC 0126}", "~")
$+SC002::AnyKey("1", "!")
$+SC003::AnyKey("{Shift Up}{RAlt Down}q{RAlt Up}{Shift Down}", "@")
$+SC004::AnyKey("{Shift Up}{#}{Shift Down}", "#")
$+SC005::AnyKey("4", "$")
$+SC006::AnyKey("5", "%")
$+SC007::AnyKey("{Shift Up}{^}{Space}{Shift Down}", "^")
$+SC008::AnyKey("6", "&")
$+SC009::AnyKey("{Shift Up}*{Shift Down}", "*")
$+SC00A::AnyKey("8", "(")
$+SC00B::AnyKey("9", ")")
$+SC00C::AnyKey("-", "_")
$+SC00D::AnyKey("{Shift Up}{+}{Shift Down}", "+")
$+SC01A::AnyKey("{Shift Up}{RAlt Down}7{RAlt Up}{Shift Down}", "{")
$+SC01B::AnyKey("{Shift Up}{RAlt Down}0{RAlt Up}{Shift Down}", "}")
$+SC028::AnyKey(2, """")
$+SC056::AnyKey("{Shift Up}{RAlt Down}<{RAlt Up}{Shift Down}", "|")
$+SC033::AnyKey("{Shift Up}<{Shift Down}", "<")
$+SC034::AnyKey("<", ">")
$+SC035::AnyKey("{Shift Up}?{Shift Down}", "?")

; special keys
$*Backspace::AnyKey("", "BS")
$*Space::AnyKey("{Space}", " ")
$*Enter::AnyKey("{Enter}", "`n")
$*Home::AnyKey("{Home}", "CL")
$*End::AnyKey("{End}", "CL")
$*PgUp::AnyKey("{PgUp}", "CL")
$*PgDn::AnyKey("{PgDn}", "CL")
$*Up::AnyKey("{Up}", "CL")
$*Down::AnyKey("{Down}", "CL")
$*Left::AnyKey("{Left}", "CL")
$*Right::AnyKey("{Right}", "CL")

; numpad
$*Numpad0::AnyKey("{Numpad0}", "0")
$*Numpad1::AnyKey("{Numpad1}", "1")
$*Numpad2::AnyKey("{Numpad2}", "2")
$*Numpad3::AnyKey("{Numpad3}", "3")
$*Numpad4::AnyKey("{Numpad4}", "4")
$*Numpad5::AnyKey("{Numpad5}", "5")
$*Numpad6::AnyKey("{Numpad6}", "6")
$*Numpad7::AnyKey("{Numpad7}", "7")
$*Numpad8::AnyKey("{Numpad8}", "8")
$*Numpad9::AnyKey("{Numpad9}", "9")
$*NumpadDot::AnyKey("{NumpadDot}", ".")
$*NumpadDiv::AnyKey("{NumpadDiv}", "/")
$*NumpadMult::AnyKey("{NumpadMult}", "*")
$*NumpadAdd::AnyKey("{NumpadAdd}", "+")
$*NumpadSub::AnyKey("{NumpadSub}", "-")
$*NumpadEnter::AnyKey("{NumpadEnter}", "`n")
$*NumpadEnd::AnyKey("{NumpadEnd}", "CL")
$*NumpadDown::AnyKey("{NumpadDown}", "CL")
$*NumpadPgDn::AnyKey("{NumpadPgDn}", "CL")
$*NumpadLeft::AnyKey("{NumpadLeft}", "CL")
$*NumpadClear::AnyKey("{NumpadClear}", "CL")
$*NumpadRight::AnyKey("{NumpadRight}", "CL")
$*NumpadHome::AnyKey("{NumpadHome}", "CL")
$*NumpadUp::AnyKey("{NumpadUp}", "CL")
$*NumpadPgUp::AnyKey("{NumpadPgUp}", "CL")
